## Linear Algrebra in Python with Numpy

In [68]:
import numpy as np

## Lists vs numpy arrays

In [69]:
alist = [1, 2, 3, 4, 5]
narray = np.array([1, 2, 3, 4])

In [70]:
print(alist)
print(narray)

print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


## Differences in algebraic operations

In [71]:
print(alist + alist)
print(narray + narray)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2 4 6 8]


In [72]:
print(alist * 3)
print(narray * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12]


## Matrixes

In [73]:
npmatrix1 = np.array([narray, narray, narray])
print(npmatrix1)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [74]:
npmatrix2 = np.array([alist, alist, alist])
print(npmatrix2)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [75]:
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray])
print(npmatrix3)

[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


However, when defining a matrix, be sure that all the rows contain the same number of elements. Otherwise, the linear algebra operations could lead to unexpected results.

Analyze the following two examples:

In [76]:
# Example 1:

okmatrix = np.array([[1, 2], [3, 4]])
print(okmatrix)
print(okmatrix * 2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [77]:
# Example 2:
# badmatrix = np.array(
# [[1, 2], [3, 4], [5, 6, 7]]
# )  # Define a matrix. Note the third row contains 3 elements
# print(badmatrix)  # Print the malformed matrix
# print(badmatrix * 2)  # It is supposed to scale the whole matrix but gives value error

## Scaling and translating matrices

In [78]:
print(okmatrix)
result = okmatrix * 2 + 1
print("-" * 10)
print(result)

[[1 2]
 [3 4]]
----------
[[3 5]
 [7 9]]


In [79]:
result1 = okmatrix + okmatrix
print(result1)

[[2 4]
 [6 8]]


In [80]:
result2 = okmatrix - okmatrix
print(result2)

[[0 0]
 [0 0]]


The product operator `*` when used on arrays or matrices indicates element-wise multiplications.
Do not confuse it with the dot product.

In [81]:
print(okmatrix)
result = okmatrix * okmatrix
print("-" * 50)
print(result)

[[1 2]
 [3 4]]
--------------------------------------------------
[[ 1  4]
 [ 9 16]]


## Transpose matrices

In [82]:
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]])
print(matrix3x2)
print(f"Original matrix has shape: {matrix3x2.shape}")
print("-" * 50)

[[1 2]
 [3 4]
 [5 6]]
Original matrix has shape: (3, 2)
--------------------------------------------------


In [83]:
print(matrix3x2.T)
print(f"Transposed original matrix has shape: {matrix3x2.T.shape}")

[[1 3 5]
 [2 4 6]]
Transposed original matrix has shape: (2, 3)


Please note that the transpose operation does not affect 1D arrays:

In [84]:
arr = np.array([1, 2, 3, 4])
print(f"Original array: {arr}")
print(f"Shape original array: {arr.shape}")
print("-" * 50)

print(f"Transposed array: {arr.T}")
print(f"Shape transposed array: {arr.T.shape}")
print("-" * 50)

Original array: [1 2 3 4]
Shape original array: (4,)
--------------------------------------------------
Transposed array: [1 2 3 4]
Shape transposed array: (4,)
--------------------------------------------------


Perhaps, in this case you may want to:

In [85]:
arr = np.array([[1, 2, 3, 4]])

print(f"Original array: {arr}")
print(f"Shape original array: {arr.shape}")
print("-" * 50)

print(f"Transposed array: \n{arr.T}")
print(f"Shape transposed array: {arr.T.shape}")
print("-" * 50)

Original array: [[1 2 3 4]]
Shape original array: (1, 4)
--------------------------------------------------
Transposed array: 
[[1]
 [2]
 [3]
 [4]]
Shape transposed array: (4, 1)
--------------------------------------------------


## Using reshape to transform singletons to one dimensional arrays

### Singleton np array unaffected with transpose

In [86]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

(5,)


In [87]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [88]:
print(arr * arr.T)
print(np.sum(arr * arr.T))

[ 1  4  9 16 25]
55


In [89]:
print(arr.T * arr)
print(np.sum(arr.T * arr))

[ 1  4  9 16 25]
55


In [90]:
print(arr @ arr)
print(arr @ arr.T)
print(arr.T @ arr)

55
55
55


### Lets see if same yields for non-singletone 1D array

In [91]:
print(f"arr: \n{arr}")
print(f"arr shape: {arr.shape}")

arr: 
[1 2 3 4 5]
arr shape: (5,)


In [92]:
arr = arr.reshape(-1, 1)
print(f"arr: \n{arr}")
print(f"arr shape: {arr.shape}")

arr: 
[[1]
 [2]
 [3]
 [4]
 [5]]
arr shape: (5, 1)


In [93]:
arr * arr

array([[ 1],
       [ 4],
       [ 9],
       [16],
       [25]])

In [102]:
print(f"arr: \n{arr}")
print("-" * 50)
print(f"arr.T: \n{arr.T}")
print("-" * 50)

arr: 
[[1]
 [2]
 [3]
 [4]
 [5]]
--------------------------------------------------
arr.T: 
[[1 2 3 4 5]]
--------------------------------------------------


In [119]:
print(f"arr: \n{arr}")
print("-" * 50)
print(f"arr.T: \n{arr.T}")
print("-" * 50)
print(f"arr * arr: \n{arr * arr}")

arr: 
[[1]
 [2]
 [3]
 [4]
 [5]]
--------------------------------------------------
arr.T: 
[[1 2 3 4 5]]
--------------------------------------------------
arr * arr: 
[[ 1]
 [ 4]
 [ 9]
 [16]
 [25]]


In [120]:
print(f"arr: \n{arr}")
print("-" * 50)
print(f"arr.T: \n{arr.T}")
print("-" * 50)
print(f"arr.T * arr: \n{arr.T * arr}")

arr: 
[[1]
 [2]
 [3]
 [4]
 [5]]
--------------------------------------------------
arr.T: 
[[1 2 3 4 5]]
--------------------------------------------------
arr.T * arr: 
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [121]:
print(f"arr: \n{arr}")
print("-" * 50)
print(f"arr.T: \n{arr.T}")
print("-" * 50)
print(f"arr * arr.T: \n{arr * arr.T}")

arr: 
[[1]
 [2]
 [3]
 [4]
 [5]]
--------------------------------------------------
arr.T: 
[[1 2 3 4 5]]
--------------------------------------------------
arr * arr.T: 
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


### Dimensions makes a difference with (x, 1) arrays

In [122]:
print(f"arr: \n{arr}")
print("-" * 50)
print(f"arr.T: \n{arr.T}")
print("-" * 50)
print(f"np.dot(arr.T, arr): \n{np.dot(arr.T, arr)}")

arr: 
[[1]
 [2]
 [3]
 [4]
 [5]]
--------------------------------------------------
arr.T: 
[[1 2 3 4 5]]
--------------------------------------------------
np.dot(arr.T, arr): 
[[55]]


In [123]:
print(f"arr: \n{arr}")
print("-" * 50)
print(f"arr.T: \n{arr.T}")
print("-" * 50)
print(f"np.dot(arr., arr.T): \n{np.dot(arr, arr.T)}")

arr: 
[[1]
 [2]
 [3]
 [4]
 [5]]
--------------------------------------------------
arr.T: 
[[1 2 3 4 5]]
--------------------------------------------------
np.dot(arr., arr.T): 
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [124]:
print(f"arr: \n{arr}")
print("-" * 50)
print(f"arr.T: \n{arr.T}")
print("-" * 50)
print(f"arr.T @ arr: {arr.T @ arr}")

arr: 
[[1]
 [2]
 [3]
 [4]
 [5]]
--------------------------------------------------
arr.T: 
[[1 2 3 4 5]]
--------------------------------------------------
arr.T @ arr: [[55]]


### Need to be careful with dimensions with x,1 arrays. See examples below

In [127]:
print(f"arr: \n{arr}")
print("-" * 50)
print(f"arr.T: \n{arr.T}")
print("-" * 50)
print(f"arr @ arr.T: \n{arr @ arr.T}")

arr: 
[[1]
 [2]
 [3]
 [4]
 [5]]
--------------------------------------------------
arr.T: 
[[1 2 3 4 5]]
--------------------------------------------------
arr @ arr.T: 
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


## Matrix norms

In [131]:
nparray1 = np.array([1, 2, 3, 4])
norm1 = np.linalg.norm(nparray1)
print(f"Norm: {norm1}")
print(f"sqrt(1^2 + 2^2 + 3^2 + 4^2): {np.sqrt(1 ** 2 + 2 ** 2 + 3 ** 2 + 4 ** 2)}")

Norm: 5.477225575051661
sqrt(1^2 + 2^2 + 3^2 + 4^2): 5.477225575051661


In [132]:
nparray1 = np.array([1, 2, 3, 4])  # Define an array
norm1 = np.linalg.norm(nparray1)

nparray2 = np.array(
    [[1, 2], [3, 4]]
)  # Define a 2 x 2 matrix. Note the 2 level of square brackets
norm2 = np.linalg.norm(nparray2)

print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


Note that without any other parameter, the norm function treats the matrix as being just an array of numbers.
However, it is possible to get the norm by rows or by columns. The **axis** parameter controls the form of the operation: 
* **axis=0** means get the norm of each column
* **axis=1** means get the norm of each row. 

In [143]:
print(f"nparray2: \n{nparray2}")
nparray2_flat = nparray2.flatten()
print(f"Flattened nparray2: \n{nparray2_flat}")
print(f"nparray2.shape: {nparray2.shape}")
print(f"nparray2_flat.shape: {nparray2_flat.shape}")
print(f"Norm nparray: {np.linalg.norm(nparray2)}")
print(f"Norm nparray_flat: {np.linalg.norm(nparray2_flat)}")

nparray2: 
[[1 1]
 [2 2]
 [3 3]]
Flattened nparray2: 
[1 1 2 2 3 3]
nparray2.shape: (3, 2)
nparray2_flat.shape: (6,)
Norm nparray: 5.291502622129181
Norm nparray_flat: 5.291502622129181


In [144]:
norm = np.linalg.norm(nparray2)
norm_flat = np.linalg.norm(nparray2.flatten())
norm_by_cols = np.linalg.norm(nparray2, axis=0)
norm_by_rows = np.linalg.norm(nparray2, axis=1)

print(f"norm: {norm}")
print(f"norm_flat: {norm_flat}")
print(f"norm_by_cols: {norm_by_cols}")
print(f"norm_by_rows: {norm_by_rows}")

norm: 5.291502622129181
norm_flat: 5.291502622129181
norm_by_cols: [3.74165739 3.74165739]
norm_by_rows: [1.41421356 2.82842712 4.24264069]


In [145]:
# Creating a 2D array with a singleton dimension
x = np.array([[[1], [2], [3], [4]]])
print(x)
print(x.shape)  # Output: (1, 4, 1)

# Applying np.squeeze
x_squeezed = np.squeeze(x)
print(x_squeezed)
print(x_squeezed.shape)  # Output: (4,)

[[[1]
  [2]
  [3]
  [4]]]
(1, 4, 1)
[1 2 3 4]
(4,)


## The dot product

In [153]:
nparray1 = np.array([0, 1, 2, 3])
nparray2 = np.array([4, 5, 6, 7])

# Recommended way
flavor1 = np.dot(nparray1, nparray2)
print(flavor1)

# Ok, way
flavour2 = np.sum(nparray1 * nparray2)
print(flavour2)

# Geeks way
flavour3 = nparray1 @ nparray2
print(flavour3)

# The NEVER EVER way
flavour4 = 0

for x, y in zip(nparray1, nparray2):
    flavour4 += x * y

print(flavour4)

38
38
38
38


**We strongly recommend using np.dot, since it is the only method that accepts arrays and lists without problems**

In [154]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4]))  # Dot product on nparrays
norm2 = np.dot([1, 2], [3, 4])  # Dot product on python lists

print(norm1, "=", norm2)

11 = 11


## Sums by rows and columns

In [156]:
nparray2 = np.array([[1, -1], [2, -2], [3, -3]])

sum_by_cols = np.sum(nparray2, axis=0)
sum_by_rows = np.sum(nparray2, axis=1)
print(f"array: \n{nparray2}")
print("-" * 50)
print(f"Sum by columns: {sum_by_cols}")
print(f"Sum by rows: {sum_by_rows}")

array: 
[[ 1 -1]
 [ 2 -2]
 [ 3 -3]]
--------------------------------------------------
Sum by columns: [ 6 -6]
Sum by rows: [0 0 0]


## Get the mean by rows or columns

In [158]:
# Mean of all items in matrix
mean = np.mean(nparray2)

# Mean of all columns
mean_cols = np.mean(nparray2, axis=0)

# Mean of all rows
mean_rows = np.mean(nparray2, axis=1)

print(mean)
print(mean_cols)
print(mean_rows)

0.0
[ 2. -2.]
[0. 0. 0.]


## Center of the columns of a matrix

In [161]:
print(nparray2)
print("-" * 50)
print(np.mean(nparray2, axis=0))
print("-" * 50)

nparray_centered = nparray2 - np.mean(nparray2, axis=0)

print(nparray_centered)

[[ 1 -1]
 [ 2 -2]
 [ 3 -3]]
--------------------------------------------------
[ 2. -2.]
--------------------------------------------------
[[-1.  1.]
 [ 0.  0.]
 [ 1. -1.]]


### Row centering

In [163]:
nparray2 = np.array([[1, 3], [2, 4], [3, 5]])  # Define a 3 x 2 matrix.
print(nparray2)
print("----")
print(np.mean(nparray2, axis=1))
print("----")
print(nparray2.T)
print("----")
nparray_row_centered = nparray2.T - np.mean(nparray2, axis=1)
print(nparray_row_centered)
nparray_row_centered = nparray_row_centered.T
print(nparray_row_centered)

[[1 3]
 [2 4]
 [3 5]]
----
[2. 3. 4.]
----
[[1 2 3]
 [3 4 5]]
----
[[-1. -1. -1.]
 [ 1.  1.  1.]]
[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]


In [164]:
# Lets test it:

np.mean(nparray_row_centered, axis=1)

array([0., 0., 0.])